# -*- coding: utf-8 -*-
"""CSE221 LAB08ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHT262xG99P1teroBG0A2hNbw90aoHXv
"""

#TASK-1
n,k=map(int,input().split())
p=[i for i in range(n+1)]
sz=[1]*(n+1)
def f(x):
 while x!=p[x]:
  p[x]=p[p[x]]
  x=p[x]
 return x
def u(x,y):
 x=f(x)
 y=f(y)
 if x!=y:
  if sz[x]<sz[y]: x,y=y,x
  p[y]=x
  sz[x]+=sz[y]
 return sz[x]
for i in range(k):
 a,b=map(int,input().split())
 if f(a)!=f(b): print(u(a,b))
 else: print(sz[f(a)])

#task-2
n,m=map(int,input().split())
e=[]
for i in range(m):
 u,v,w=map(int,input().split())
 e.append((w,u,v))
e.sort()
p=[i for i in range(n+1)]
def find(x):
 while x!=p[x]:
  p[x]=p[p[x]]
  x=p[x]
 return x
def union(x,y):
 x=find(x)
 y=find(y)
 if x!=y:
  p[y]=x
  return True
 return False
res=0
for w,u,v in e:
 if                                                                                                                                                                                                    union(u,v): res+=w
print(res)
